# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 103007873b287a4b62e67d4bab2852be54128d223ecb9c9b9a05976bc8f24ac9cd05f6c1065f5cce0232f18bfc06e3ef8dcc48f08edf9c78b9c91072e106be98

test:
  secret_key_base: faa4bd2e30fd56a4e3ab49feda54021659c50f7ac548b3362d135c54fec5460a3f9debd7e827a5c0d57533436e05d877f58aca107c230b3d965db22c8f78823a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
